version: '2'

services:
  react-stack:
    build: .
    volumes:
      - ./:/usr/workdir/
    environment:
      - FORCE_COLOR=1
    env_file:
      - .env
    ports:
      - "3000:3000"
      - "8080:8080"
